### ISSUE TITLE
[Mantine UI series] Transition

### ISSUE THREAD

**Issue by reboottime** [reboottime/react-daily#3]

**Comment by reboottime** [comment]
## How CSS Transition works

1. You declare the transition works on which property with what kind of animation function and duration 
2. Triggering change on the transition property which triggers the transition 

For example

```css
.block {
   background: red;
   height: 100px;
   width: 100px;
   transition: background-color 
}

.block.warning {

}
```
